// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/login","layout":false,"id":"1"},"2":{"path":"/","redirect":"/dashboard","parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"数据看板","path":"/dashboard","icon":"DashboardOutlined","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"博物馆管理","path":"/museum","icon":"BankOutlined","parentId":"ant-design-pro-layout","id":"4"},"5":{"name":"博物馆列表","path":"/museum/list","parentId":"4","id":"5"},"6":{"name":"省市管理","path":"/museum/city","parentId":"4","id":"6"},"7":{"name":"内容管理","path":"/content","icon":"FileTextOutlined","parentId":"ant-design-pro-layout","id":"7"},"8":{"name":"UGC审核","path":"/content/ugc","parentId":"7","id":"8"},"9":{"name":"评论管理","path":"/content/comment","parentId":"7","id":"9"},"10":{"name":"用户管理","path":"/user","icon":"UserOutlined","parentId":"ant-design-pro-layout","id":"10"},"11":{"name":"用户列表","path":"/user/list","parentId":"10","id":"11"},"12":{"name":"管理员","path":"/user/admin","parentId":"10","id":"12"},"13":{"name":"系统设置","path":"/settings","icon":"SettingOutlined","parentId":"ant-design-pro-layout","id":"13"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__Login__index" */'@/pages/Login/index.tsx')),
'2': React.lazy(() => import('./EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Dashboard__index" */'@/pages/Dashboard/index.tsx')),
'4': React.lazy(() => import('./EmptyRoute')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Museum__List__index" */'@/pages/Museum/List/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Museum__City__index" */'@/pages/Museum/City/index.tsx')),
'7': React.lazy(() => import('./EmptyRoute')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Content__UGC__index" */'@/pages/Content/UGC/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Content__Comment__index" */'@/pages/Content/Comment/index.tsx')),
'10': React.lazy(() => import('./EmptyRoute')),
'11': React.lazy(() => import(/* webpackChunkName: "p__User__List__index" */'@/pages/User/List/index.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__User__Admin__index" */'@/pages/User/Admin/index.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__Settings__index" */'@/pages/Settings/index.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "t__plugin-layout__Layout" */'/root/.openclaw/workspace/team/pm-lead/projects/museum-admin/src/.umi-production/plugin-layout/Layout.tsx')),
},
  };
}
