// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DashboardOutlined from '/root/.openclaw/workspace/team/pm-lead/projects/museum-admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import BankOutlined from '/root/.openclaw/workspace/team/pm-lead/projects/museum-admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/BankOutlined';
import FileTextOutlined from '/root/.openclaw/workspace/team/pm-lead/projects/museum-admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/FileTextOutlined';
import UserOutlined from '/root/.openclaw/workspace/team/pm-lead/projects/museum-admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/UserOutlined';
import SettingOutlined from '/root/.openclaw/workspace/team/pm-lead/projects/museum-admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/SettingOutlined';
export default { DashboardOutlined, BankOutlined, FileTextOutlined, UserOutlined, SettingOutlined };
